import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { format } from 'date-fns';

// Add type support for autotable
declare module 'jspdf' {
    interface jsPDF {
        autoTable: (options: any) => jsPDF;
    }
}

interface ReportData {
    formTitle: string;
    formDescription?: string;
    responses: any[];
    fields: any[];
    generatedBy: string;
}

export const generateAttendancePDF = (data: ReportData) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const date = format(new Date(), 'PPP');

    // --- HEADER SECTION ---
    // Branded bar at top
    doc.setFillColor(79, 70, 229); // Violet-600
    doc.rect(0, 0, pageWidth, 40, 'F');

    // Church Name & Branding
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('CHRIST LOVE BREED CHURCH', 15, 20);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('LOGISTICS & STATISTICS RESOURCE PORTAL', 15, 28);

    // Report Label
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('OFFICIAL ATTENDANCE REPORT', pageWidth - 15, 25, { align: 'right' });

    // --- REPORT METADATA ---
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(18);
    doc.text(data.formTitle.toUpperCase(), 15, 55);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(`Description: ${data.formDescription || 'N/A'}`, 15, 62);

    doc.text(`Generated on: ${date}`, 15, 68);
    doc.text(`Generated by: ${data.generatedBy}`, 15, 74);
    doc.text(`Total Attendees: ${data.responses.length}`, pageWidth - 15, 74, { align: 'right' });

    // --- TABLE SECTION ---
    const tableHeaders = data.fields.map(f => f.label);
    const tableData = data.responses.map(r => {
        return data.fields.map(f => {
            const val = r.response_data?.[f.id];
            if (val === undefined || val === null || val === '') return '-';
            if (typeof val === 'boolean') return val ? 'Yes' : 'No';
            if (typeof val === 'object') return JSON.stringify(val);
            return String(val);
        });
    });

    doc.autoTable({
        startY: 85,
        head: [tableHeaders],
        body: tableData,
        theme: 'striped',
        headStyles: {
            fillColor: [79, 70, 229], // Violet-600
            textColor: [255, 255, 255],
            fontSize: 10,
            fontStyle: 'bold',
            halign: 'left'
        },
        bodyStyles: {
            fontSize: 9,
            textColor: [50, 50, 50]
        },
        alternateRowStyles: {
            fillColor: [248, 250, 252] // slate-50
        },
        margin: { top: 20 },
        didDrawPage: (data: any) => {
            // Footer
            doc.setFontSize(8);
            doc.setTextColor(150, 150, 150);
            doc.text(
                `Page ${doc.getNumberOfPages()}`,
                pageWidth / 2,
                doc.internal.pageSize.getHeight() - 10,
                { align: 'center' }
            );
        }
    });

    // Save the PDF
    const fileName = `CLBC-Report-${data.formTitle.replace(/\s+/g, '-')}-${format(new Date(), 'yyyy-MM-dd')}.pdf`;
    doc.save(fileName);
};
